### ISSUE TITLE
Modify User-Agent string to include incoming data

### ISSUE THREAD

**Issue by loketan-zz** [skytap/skytap-sdk-go#38]
In order to allow our API to track calls coming from different clients through the SDK, we need to accept the incoming `User-Agent` string from SDK clients (eg. terraform), and append it to the outgoing `User-Agent` string to Skytap APIs. 

Terraform client's User-Agent: `tf-1.0.0`
Go SDK -> API User-Agent: `skytap-go-sdk/tf-1.0.0`

**Comment by ja6a** [comment]
Ready to be closed once PR #41 merged
